config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  get 'welcome/index'

  devise_for :users
  resources :users

  root 'welcome#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def edit
		@user = current_user
	end

	def update
		@user = current_user

		if @user.update(user_params)
			redirect_to edit_profile_path, notice: 'Updated your profile.'
		else
			flash.now[:alert] = @user.errors.full_messages.join('. ')
			render :edit
		end
	end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tweets = Tweet.all
    respond_with(@tweets)
  end

  def show
    respond_with(@tweet)
  end

  def new
    @tweet = Tweet.new
    respond_with(@tweet)
  end

  def edit
  end

  def create
    @tweet = current_user.tweets.create(tweet_params)
    respond_with(@tweet)
  end

  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@tweets = Tweet.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper


def resource_name

:user

end



def resource

@resource ||= User.new

end



def devise_mapping

@devise_mapping ||= Devise.mappings[:user]

end



end

app/views/layouts/_flashes.html.erb
<% if notice.present? %>
<div class="alert alert-success" role="alert"><%= notice %></div>
<% elsif alert.present? %>
<div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TechTalentTwitter</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/clean-blog.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

	<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/welcome/index">Tech Talent Twitter</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
						<li>
						<p class="navbar-text">Hi, <%= current_user.handle %>!</p>
						</li>
						<li>
						<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
						</li>
					<% else %>
						<li>
						<%= link_to 'Log In', new_user_session_path %>
						</li>
						<li>
						<%= link_to 'Sign Up', new_user_registration_path %>
						</li>
					<% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<%= asset_path('twitter.jpg')%>')">

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->

    <div class="container">
		<%= render 'layouts/flashes' %>
		<%= yield %>
	</div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<li class="tweet">
	<div class="media">
		<div class="media-left">
			<%= link_to tweet.user do %>
		<% end %>
	</div>

	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to tweet.user.handle, tweet.user %>
			<!-- <small>< tweet_date(tweet) ></small> -->
		</h4>
		<p><%= tweet.body %></p>
	</div>
</div>
</li>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.body %></td>
        <td><%= tweet.user %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/show.html.erb
<div class="page-header">
	<h1><%= @user.handle %></h1>
</div>

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default user-tweets">
			<div class="panel-heading">
				<h3 class="panel-title">Recent Tweets</h3>
			</div>
		
			<div class="panel-body">
				<ul class="tweets list-unstyled">
					<%= render @user.recent_tweets %>
				</ul>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default user-profile">
			<div class="panel-heading">
				<h3 class="panel-title">Profile</h3>
			</div>

			<div class="panel-body">
				<dl>
					<dt>Name</dt>
					<dd><%= @user.name %></dd>

					<dt>Email</dt>
					<dd><%= @user.email %></dd>

					<dt>Location</dt>
					<dd><%= @user.location %></dd>

					<dt>Tweets</dt>
					<dd><%= @user.tweets.count %></dd>

				</dl>
			</div>
		</div>
	</div>
</div>

app/views/welcome/_signin.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>

	<p><strong>Email:</strong> <%= f.text_field :email %></p>
	<p><strong>Password:</strong> <%= f.password_field :password %></p>
	<p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>
	<p><%= f.submit 'Sign In' %></p>
	<p><%= link_to "Forgot your password?", new_password_path(:user) %></p>

<% end %>

app/views/welcome/_signup.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

	<%= devise_error_messages! %>

	<p><%= f.label :email %><br />
	<%= f.email_field :email, autofocus: true %></p>

	<p><%= f.label :name %><br />
	<%= f.text_field :name %></p>

	<p><%= f.label :password %><br />
	<%= f.password_field :password, autocomplete: "off" %></p>

	<p><%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation, autocomplete: "off" %></p>

	<div><%= f.submit "Sign up" %></div>

<% end %>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Everyone's Tweets</h1>
</div>

<ul class="tweets list-unstyled">
  <%= render @tweets %>
</ul>

<%= link_to 'New Tweet', new_tweet_path %>